name: CI with Jira comment
on:
  push:
    branches: [ "**" ]   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Demo build/test
      - name: Run tests (demo)
        run: echo "tests passed"

  
      - name: Extract Jira key from branch/commit
        id: jirakey
        run: |
          REF="${GITHUB_REF_NAME}"
          MSG="$(git log -1 --pretty=%B)"
          KEY="$(echo "$REF $MSG" | grep -oE '[A-Z]+-[0-9]+' | head -1 || true)"
          echo "key=$KEY" >> "$GITHUB_OUTPUT"

      - name: Post comment to Jira
        if: steps.jirakey.outputs.key != ''   # ya PROJ-4 hardcode ho to bhi chalega
        env:
          JIRA_SITE: ${{ secrets.JIRA_SITE }}        # https://<your>.atlassian.net
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          AUTH=$(printf "%s:%s" "$JIRA_EMAIL" "$JIRA_API_TOKEN" | base64 -w 0)
          BODY=$(jq -cn --arg txt "✅ CI passed for ${GITHUB_REPOSITORY}@${GITHUB_SHA::7}" '{body:$txt}')

          ISSUE="${{ steps.jirakey.outputs.key }}"   # ya ISSUE="PROJ-4"
          URL="$JIRA_SITE/rest/api/3/issue/$ISSUE/comment"

          # debug (optional): echo "$URL"
          curl -sS -f -X POST "$URL" \
            -H "Authorization: Basic $AUTH" \
            -H "Content-Type: application/json" \
            --data "$BODY"
